(define (problem pleasant_office_room)
    (:domain office_room)
    (:requirements :conditional-effects :disjunctive-preconditions :equality :fluents :negative-preconditions :strips :typing)
    (:init (= (force_cooler) 1) (= (force_light) 1) (= (force_window) 1) (= (humidity) 56) (= (inside_temp) 28.9) (= (light) 43) (= (outside_temp) 21) (= (water_level) 10) (light_on) (not (air_cooler_on)) (not (is_raining)) (windows_open) (z_end_predicate))
    (:goal (or (light_action_done) (window_action_done) (cooler_action_done) (no_action_possible)))
)